export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_ADDRESS = 'GET_USER_ADDRESS';
export const GET_ERRORS_ALLURS = 'GET_ERRORS_ALLURS';